name: "Nuclei Scanner"

on:
  workflow_dispatch:
    inputs:
      target_name:
        description: 'Name of target folder in storage repo'
        required: true
      storage_repo:
        description: 'SSH URL of scan-results-storage repo'
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Install Nuclei
        run: go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest

      - name: Setup SSH
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "${DEPLOY_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone Storage Repo
        run: git clone ${{ github.event.inputs.storage_repo }} storage_repo_clone

      - name: Run Nuclei Scan
        run: |
          set -e
          TARGET_NAME=${{ github.event.inputs.target_name }}
          URL_FILE_PATH="storage_repo_clone/$TARGET_NAME/discovery/live-urls.txt"
          OUTPUT_FILE="nuclei-output.txt"

          if [ ! -f "$URL_FILE_PATH" ]; then
            echo "URL file not found: $URL_FILE_PATH"
            exit 1
          fi

          echo "Starting Nuclei scan..."
          ~/go/bin/nuclei -l "$URL_FILE_PATH" -o "$OUTPUT_FILE" -silent

          echo "Nuclei scan complete. Output saved to $OUTPUT_FILE"

      - name: Push results to storage repo
        run: |
          cd storage_repo_clone
          mkdir -p ${{ github.event.inputs.target_name }}/xss
          mv ../nuclei-output.txt ${{ github.event.inputs.target_name }}/xss/nuclei.txt
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          if ! git diff --staged --quiet; then
            git commit -m "Add Nuclei scan results for ${{ github.event.inputs.target_name }}"
            git push
          else
            echo "No changes to commit"
          fi
