name: "Nuclei Scanner"

on:
  workflow_dispatch:
    inputs:
      target_name:
        description: 'Name of target folder in storage repo'
        required: true
      storage_repo:
        description: 'SSH URL of scan-results-storage repo'
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nuclei
        run: go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest

      - name: Setup SSH and Git
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "${DEPLOY_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Clone Storage Repo
        run: git clone ${{ github.event.inputs.storage_repo }} storage_repo

      - name: Run Nuclei Scan
        run: |
          set -e
          URL_FILE="storage_repo/${{ github.event.inputs.target_name }}/discovery/live-urls.txt"
          OUTPUT_FILE="nuclei-output.txt"

          if [ ! -f "$URL_FILE" ]; then
            echo "URL file not found: $URL_FILE"
            exit 1
          fi

          echo "Starting Nuclei scan..."
          ~/go/bin/nuclei -l "$URL_FILE" -o "$OUTPUT_FILE" -silent
          echo "Nuclei scan complete. Output saved to $OUTPUT_FILE"

      - name: Push results to storage repo
        run: |
          cd storage_repo
          TARGET_DIR="${{ github.event.inputs.target_name }}/xss"
          mkdir -p "$TARGET_DIR"
          mv ../nuclei-output.txt "$TARGET_DIR/nuclei.txt"

          if ! git diff --quiet; then
            git add .
            git commit -m "Add Nuclei scan results for ${{ github.event.inputs.target_name }}"
            git push
          else
            echo "No changes to commit"
          fi
